"""
Django settings for zololenta project.

Generated by 'django-admin startproject' using Django 5.2.3.
"""

from pathlib import Path
from decouple import config
from decouple import Csv


# =========================
# Base
# =========================
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = config("SECRET_KEY")
DEBUG = config("DEBUG", cast=bool, default=False)

ALLOWED_HOSTS = [
    "zololenta.ru",
    "www.zololenta.ru",
]

CSRF_TRUSTED_ORIGINS = [
    "https://zololenta.ru",
    "https://www.zololenta.ru",
]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", cast=bool, default=True)
SESSION_COOKIE_SECURE = config("SESSION_COOKIE_SECURE", cast=bool, default=True)
CSRF_COOKIE_SECURE = config("CSRF_COOKIE_SECURE", cast=bool, default=True)

SECURE_HSTS_SECONDS = config("SECURE_HSTS_SECONDS", cast=int, default=31536000)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config("SECURE_HSTS_INCLUDE_SUBDOMAINS", cast=bool, default=True)
SECURE_HSTS_PRELOAD = config("SECURE_HSTS_PRELOAD", cast=bool, default=True)

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
X_FRAME_OPTIONS = "DENY"


# =========================
# Apps
# =========================
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",

    "main.apps.MainConfig",
    "users",

    "django_ckeditor_5",
    "import_export",
    "phonenumber_field",

    "allauth",
    "allauth.account",
    "allauth.socialaccount",

    "django_admin_geomap",

    "dal",
    "dal_select2",
    "django_select2",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django_webp.middleware.ModdedWhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "zololenta.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "main" / "templates",
            "/home/j/joker2038/zololenta/public_html/venv/lib/python3.10/site-packages/django_admin_geomap/templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django_webp.context_processors.webp",
                "main.context_processors.subscriber_form",
            ],
        },
    },
]

WSGI_APPLICATION = "zololenta.wsgi.application"


# =========================
# Database
# =========================
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": config("DATABASE_NAME"),
        "USER": config("DATABASE_USER"),
        "PASSWORD": config("DATABASE_PASSWORD"),
        "HOST": config("DATABASE_HOST"),
        "PORT": config("DATABASE_PORT"),
        "OPTIONS": {"init_command": "SET sql_mode='STRICT_TRANS_TABLES'"},
        "TEST": {
            "NAME": "joker2038_test",
            "USER": "joker2038_test",
            "PASSWORD": config("DATABASE_TEST_PASSWORD"),
            "HOST": config("DATABASE_HOST", default="localhost"),
            "PORT": config("DATABASE_PORT", default="3306"),
        },
    }
}


# =========================
# Auth / Passwords
# =========================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# =========================
# I18N / TZ
# =========================
LANGUAGE_CODE = "ru-ru"
TIME_ZONE = "Europe/Moscow"
USE_I18N = True
USE_TZ = True


# =========================
# Static / Media
# =========================
STATIC_URL = "static/"
STATIC_ROOT = "/home/j/joker2038/zololenta/public_html/static/"

MEDIA_URL = "/media/"
MEDIA_ROOT = "/home/j/joker2038/zololenta/public_html/media/"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# =========================
# Email
# =========================
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_PORT = config("EMAIL_PORT", cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", cast=bool, default=False)
EMAIL_USE_SSL = config("EMAIL_USE_SSL", cast=bool, default=False)
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")


# =========================
# Sites / Allauth
# =========================
SITE_ID = config("SITE_ID", cast=int, default=1)

ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 1
ACCOUNT_USERNAME_MIN_LENGTH = 4
LOGIN_REDIRECT_URL = "index"

ACCOUNT_FORMS = {
    "login": "main.forms.CustomLoginForm",
    "reset_password": "main.forms.CustomResetPasswordForm",
}

ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_UNIQUE_EMAIL = True


# =========================
# Telegram
# =========================
TELEGRAM_ENABLED = config("TELEGRAM_ENABLED", cast=bool, default=False)
TELEGRAM_BOT_TOKEN = config("TELEGRAM_BOT_TOKEN", default="")

# ВАЖНО: список id как int
TELEGRAM_ADMIN_IDS = config("TELEGRAM_ADMIN_IDS", cast=Csv(int), default="")

TELEGRAM_API_TIMEOUT = config("TELEGRAM_API_TIMEOUT", cast=int, default=10)
TELEGRAM_PARSE_MODE = config("TELEGRAM_PARSE_MODE", default="MarkdownV2")
TELEGRAM_ORDERS_CHAT_ID = config("TELEGRAM_ORDERS_CHAT_ID", cast=int, default=0)
TELEGRAM_USE_TOPICS = config("TELEGRAM_USE_TOPICS", cast=bool, default=True)
TELEGRAM_THROTTLE_SECONDS = config("TELEGRAM_THROTTLE_SECONDS", cast=int, default=10)

if TELEGRAM_ENABLED and not TELEGRAM_ORDERS_CHAT_ID:
    raise RuntimeError("TELEGRAM_ENABLED=True but TELEGRAM_ORDERS_CHAT_ID is empty")


if TELEGRAM_ENABLED and not TELEGRAM_BOT_TOKEN:
    raise RuntimeError("TELEGRAM_ENABLED=True but TELEGRAM_BOT_TOKEN is empty")


# =========================
# CKEditor 5
# =========================
customColorPalette = [
    {"color": "hsl(4, 90%, 58%)", "label": "Red"},
    {"color": "hsl(340, 82%, 52%)", "label": "Pink"},
    {"color": "hsl(291, 64%, 42%)", "label": "Purple"},
    {"color": "hsl(262, 52%, 47%)", "label": "Deep Purple"},
    {"color": "hsl(231, 48%, 48%)", "label": "Indigo"},
    {"color": "hsl(207, 90%, 54%)", "label": "Blue"},
]

CKEDITOR_5_ALLOW_ALL_FILE_TYPES = True
CKEDITOR_5_FILE_UPLOAD_PERMISSION = "staff"
CKEDITOR_5_CUSTOM_CSS = "css/ckeditor5/admin_dark_mode_fix.css"

_CKEDITOR_BASE = {
    "removePlugins": ["WordCount"],
    "toolbar": [
        "heading", "|",
        "bold", "italic", "link", "|",
        "bulletedList", "numberedList", "|",
        "blockQuote", "insertTable", "|",
        "imageUpload", "|",
        "undo", "redo",
    ],
    "heading": {
        "options": [
            {"model": "paragraph", "title": "Абзац", "class": "ck-heading_paragraph"},
            {"model": "heading1", "view": "h1", "title": "Заголовок 1", "class": "ck-heading_heading1"},
            {"model": "heading2", "view": "h2", "title": "Заголовок 2", "class": "ck-heading_heading2"},
            {"model": "heading3", "view": "h3", "title": "Заголовок 3", "class": "ck-heading_heading3"},
        ]
    },
    "table": {
        "contentToolbar": ["tableColumn", "tableRow", "mergeTableCells"]
    },
    "fontColor": {"colors": customColorPalette},
    "fontBackgroundColor": {"colors": customColorPalette},
}

CKEDITOR_5_CONFIGS = {
    "default": _CKEDITOR_BASE,
    "extends": _CKEDITOR_BASE,
}
