# Generated by Django 5.2.4 on 2025-07-10 13:01

import django.db.models.deletion
import django_ckeditor_5.fields
import main.fields
import main.mixins
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория лекции',
                'verbose_name_plural': 'Категории лекций',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CategoryNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория новости',
                'verbose_name_plural': 'Категории новостей',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CategoryProg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория проектов',
                'verbose_name_plural': 'Категории проектов',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Группа контактов',
                'verbose_name_plural': 'Группы контактов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Раздел сайта')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Раздел сайта',
                'verbose_name_plural': 'Разделы сайта',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True)),
                ('unsubscribe_token', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Подписчика',
                'verbose_name_plural': 'Подписчики',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основной контакт')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Contact', to='users.location', verbose_name='Местоположение')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='main.contactgroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.contact', verbose_name='Контактное лицо')),
            ],
            options={
                'verbose_name': 'Запрос на контакт',
                'verbose_name_plural': 'Запросы на контакт',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('photo', main.fields.WEBPField(blank=True, null=True, upload_to=main.models.image_folder, verbose_name='Фото')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Текст')),
                ('photo2', main.fields.WEBPField(blank=True, null=True, upload_to=main.models.image_folder, verbose_name='Фото2')),
                ('photo3', main.fields.WEBPField(blank=True, null=True, upload_to=main.models.image_folder, verbose_name='Фото3')),
                ('photo4', main.fields.WEBPField(blank=True, null=True, upload_to=main.models.image_folder, verbose_name='Фото4')),
                ('prog_statement', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Положение о проекте')),
                ('photo5', main.fields.WEBPField(blank=True, null=True, upload_to=main.models.image_folder, verbose_name='Фото5')),
                ('prog_statement2', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Положение о проекте 2 абзац')),
                ('name_pdffile', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя PDF файла')),
                ('pdffile', models.FileField(blank=True, null=True, upload_to='pdf/%Y/%m/%d/', verbose_name='PDF')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('time_start', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время начала проекта')),
                ('time_ending', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания проекта')),
                ('is_published', models.BooleanField(verbose_name='Публикация')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.categoryprog', verbose_name='Категория')),
                ('registration', models.ManyToManyField(blank=True, related_name='progs', to=settings.AUTH_USER_MODEL, verbose_name='Участники проекта')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervisor', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['time_create', 'title'],
            },
            bases=(main.mixins.OccupancyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Текст')),
                ('photo', main.fields.WEBPField(blank=True, null=True, upload_to=main.models.image_folder, verbose_name='фото 633x550px')),
                ('content2', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст2')),
                ('photo2', main.fields.WEBPField(blank=True, null=True, upload_to=main.models.image_folder, verbose_name='фото2')),
                ('photo3', main.fields.WEBPField(blank=True, null=True, upload_to=main.models.image_folder, verbose_name='Фото№3')),
                ('content3', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст3')),
                ('photo4', main.fields.WEBPField(blank=True, null=True, upload_to=main.models.image_folder, verbose_name='Фото№4')),
                ('photo5', main.fields.WEBPField(blank=True, null=True, upload_to=main.models.image_folder, verbose_name='Фото№5')),
                ('content4', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст4')),
                ('time_create', models.DateTimeField(verbose_name='Дата и время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.categorynews', verbose_name='Категория')),
                ('prog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.prog', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['time_create', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст')),
                ('URL', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.categorylecture', verbose_name='Категория')),
                ('prog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.prog', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Лекции',
                'verbose_name_plural': 'Лекции',
                'ordering': ['time_create', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Имя')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('body', models.TextField(verbose_name='Отзыв')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review', to='main.prog', verbose_name='Название проекта')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Текст')),
                ('name_pdffile', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя PDF файла')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdf/%Y/%m/%d/', verbose_name='Файл')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('section', models.ManyToManyField(blank=True, related_name='Документы', to='main.section', verbose_name='Раздел сайта')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['time_create'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Текст')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Цена')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото2')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото3')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото4')),
                ('photo5', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото5')),
                ('photo6', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото6')),
                ('time_create', models.DateTimeField(verbose_name='Дата и время создания')),
                ('time_update', models.DateTimeField(verbose_name='Дата и время обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('number_of_employees', models.IntegerField(default=0, verbose_name='Количество сотрудников')),
                ('executor', models.ManyToManyField(blank=True, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'unique_together': {('title', 'slug')},
            },
        ),
    ]
