# Generated by Django 5.2.4 on 2026-01-12 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='contactgroup',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Группа контактов', 'verbose_name_plural': 'Группы контактов'},
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ['email'], 'verbose_name': 'Подписчик', 'verbose_name_plural': 'Подписчики'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='users.location', verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='main.contact', verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна ли подписка'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='subscribed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='unsubscribe_token',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Токен для отписки'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['is_main'], name='idx_contact_is_main'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['group', 'order'], name='idx_contact_group_order'),
        ),
        migrations.AddIndex(
            model_name='contactrequest',
            index=models.Index(fields=['created_at'], name='idx_contactreq_created_at'),
        ),
        migrations.AddIndex(
            model_name='contactrequest',
            index=models.Index(fields=['contact'], name='idx_contactreq_contact'),
        ),
        migrations.AddIndex(
            model_name='subscriber',
            index=models.Index(fields=['email'], name='idx_subscriber_email'),
        ),
        migrations.AddIndex(
            model_name='subscriber',
            index=models.Index(fields=['is_active'], name='idx_subscriber_active'),
        ),
    ]
