# Generated by Django 5.2.4 on 2026-01-25 09:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_contact_options_alter_contactgroup_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RibbonOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt_type', models.CharField(choices=[('color', 'Цвет'), ('font', 'Шрифт')], max_length=10, verbose_name='Тип опции')),
                ('css_value', models.CharField(blank=True, default='', max_length=100, verbose_name='CSS значение')),
                ('font_url', models.URLField(blank=True, default='', verbose_name='URL шрифта (если нужно)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ribbon_option', to='main.news', verbose_name='Новость-опция')),
            ],
            options={
                'verbose_name': 'Опция конструктора лент',
                'verbose_name_plural': 'Опции конструктора лент',
                'indexes': [models.Index(fields=['opt_type', 'is_active'], name='idx_ribbonopt_type_active')],
            },
        ),
        migrations.CreateModel(
            name='RibbonOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('text', models.CharField(max_length=120, verbose_name='Текст на ленте')),
                ('name', models.CharField(blank=True, default='', max_length=80, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('color_news', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ribbon_orders_color', to='main.news', verbose_name='Цвет (новость)')),
                ('font_news', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ribbon_orders_font', to='main.news', verbose_name='Шрифт (новость)')),
            ],
            options={
                'verbose_name': 'Заказ ленты',
                'verbose_name_plural': 'Заказы лент',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='idx_ribbonorder_created')],
            },
        ),
    ]
