# Generated by Django 5.2.4 on 2026-01-25 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ribbonoption_ribbonorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='ribbonorder',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий/пожелания'),
        ),
        migrations.AddField(
            model_name='ribbonorder',
            name='edit_token',
            field=models.CharField(db_index=True, default='9b19841daea24f7aae95388424ac505c', max_length=64, unique=True, verbose_name='Токен редактирования'),
        ),
        migrations.AddField(
            model_name='ribbonorder',
            name='is_group_order',
            field=models.BooleanField(default=False, verbose_name='Групповой заказ'),
        ),
        migrations.AddField(
            model_name='ribbonorder',
            name='manager_note',
            field=models.TextField(blank=True, default='', verbose_name='Заметка менеджера'),
        ),
        migrations.AddField(
            model_name='ribbonorder',
            name='persons_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Кол-во лент/человек'),
        ),
        migrations.AddField(
            model_name='ribbonorder',
            name='persons_list',
            field=models.TextField(blank=True, default='', help_text='Одна строка = один человек. Например: Иванов Иван Иванович', verbose_name='Список ФИО (по строкам)'),
        ),
        migrations.AddField(
            model_name='ribbonorder',
            name='source',
            field=models.CharField(blank=True, default='site', help_text='Например: site / instagram / whatsapp', max_length=50, verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='ribbonorder',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('wait_approval', 'Ожидает согласования'), ('done', 'Завершена'), ('archived', 'Архив')], db_index=True, default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='ribbonorder',
            name='text_color',
            field=models.CharField(default='#FFFFFF', help_text='Например: #FFFFFF или #000000', max_length=7, verbose_name='Цвет текста (HEX)'),
        ),
        migrations.AddField(
            model_name='ribbonorder',
            name='tg_chat_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='TG chat_id (карточка)'),
        ),
        migrations.AddField(
            model_name='ribbonorder',
            name='tg_last_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация с TG'),
        ),
        migrations.AddField(
            model_name='ribbonorder',
            name='tg_lock_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='TG lock until'),
        ),
        migrations.AddField(
            model_name='ribbonorder',
            name='tg_message_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='TG message_id (карточка)'),
        ),
        migrations.AddField(
            model_name='ribbonorder',
            name='tg_thread_root_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Если будешь делать треды/форумы: сюда кладёшь ID корневого сообщения/темы', null=True, verbose_name='TG root_message_id (тред/чат заявки)'),
        ),
        migrations.AddField(
            model_name='ribbonorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='ribbonoption',
            name='css_value',
            field=models.CharField(blank=True, default='', help_text='Для цвета: #RRGGBB. Для шрифта: font-family, например: Montserrat, sans-serif', max_length=150, verbose_name='CSS значение'),
        ),
        migrations.AlterField(
            model_name='ribbonoption',
            name='font_url',
            field=models.URLField(blank=True, default='', help_text="Только для opt_type=font. Вставляй URL на CSS, который подключается через <link rel='stylesheet'>", verbose_name='URL шрифта (stylesheet)'),
        ),
        migrations.AlterField(
            model_name='ribbonoption',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='ribbonoption',
            name='opt_type',
            field=models.CharField(choices=[('color', 'Цвет ленты'), ('font', 'Шрифт')], db_index=True, max_length=10, verbose_name='Тип опции'),
        ),
        migrations.AlterField(
            model_name='ribbonorder',
            name='color_news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ribbon_orders_color', to='main.news', verbose_name='Цвет ленты (новость)'),
        ),
        migrations.AlterField(
            model_name='ribbonorder',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Контактное лицо'),
        ),
        migrations.AddIndex(
            model_name='ribbonorder',
            index=models.Index(fields=['status', 'created_at'], name='idx_ribbonorder_status_created'),
        ),
    ]
