# Generated by Django 5.2.4 on 2026-01-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ribbonorder_comment_ribbonorder_edit_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ribbonorder',
            name='foil',
            field=models.CharField(choices=[('none', 'Без фольги'), ('gold', 'Фольга золото'), ('silver', 'Фольга серебро')], default='none', max_length=10, verbose_name='Фольга (эффект печати)'),
        ),
        migrations.AlterField(
            model_name='ribbonorder',
            name='edit_token',
            field=models.CharField(db_index=True, default='b93822adb2994ba499c538b1b53e5c45', max_length=64, unique=True, verbose_name='Токен редактирования'),
        ),
    ]
