# Generated by Django 5.2.4 on 2026-01-27 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_ribbonorder_foil_alter_ribbonorder_edit_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='ribbonorder',
            name='font_family',
            field=models.CharField(blank=True, default="'Montserrat', sans-serif", help_text="Например: 'Montserrat', sans-serif", max_length=120, verbose_name='Шрифт (CSS font-family)'),
        ),
        migrations.AddField(
            model_name='ribbonorder',
            name='ribbon_bg',
            field=models.CharField(blank=True, default='#1E4ED8', help_text='Например: #1E4ED8', max_length=7, verbose_name='Цвет ленты (HEX)'),
        ),
        migrations.AlterField(
            model_name='ribbonorder',
            name='color_news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ribbon_orders_color', to='main.news', verbose_name='Цвет ленты (новость, legacy)'),
        ),
        migrations.AlterField(
            model_name='ribbonorder',
            name='edit_token',
            field=models.CharField(db_index=True, default='779f5d2af1514201a886d03248507ae0', max_length=64, unique=True, verbose_name='Токен редактирования'),
        ),
        migrations.AlterField(
            model_name='ribbonorder',
            name='font_news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ribbon_orders_font', to='main.news', verbose_name='Шрифт (новость, legacy)'),
        ),
    ]
