# Generated by Django 5.2.4 on 2026-02-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_ribbonorder_font_family_ribbonorder_ribbon_bg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ribbonorder',
            name='edit_token',
            field=models.CharField(db_index=True, default='453df6a14287451ea6c61d9857c0dd36', max_length=64, unique=True, verbose_name='Токен редактирования'),
        ),
    ]
