# Generated by Django 5.2.4 on 2026-07-05 15:58

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_ribbonorder_edit_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ribbonorder',
            name='edit_token',
            field=models.CharField(db_index=True, default=main.models.generate_edit_token, max_length=64, unique=True, verbose_name='Токен редактирования'),
        ),
    ]
