# Generated by Django 5.2.4 on 2026-07-09 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_order_review_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='RibbonOrderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(5, '5 — отлично'), (4, '4 — хорошо'), (3, '3 — нормально'), (2, '2 — плохо'), (1, '1 — очень плохо')], default=5, verbose_name='Оценка')),
                ('body', models.TextField(verbose_name='Отзыв')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reviews/%Y/%m/%d/', verbose_name='Фото')),
                ('active', models.BooleanField(db_index=True, default=False, help_text='Отзыв появляется на сайте только после публикации.', verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_review', to='main.ribbonorder', verbose_name='Заказ ленты')),
            ],
            options={
                'verbose_name': 'Отзыв по заказу ленты',
                'verbose_name_plural': 'Отзывы по заказам лент',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AddIndex(
            model_name='ribbonorderreview',
            index=models.Index(fields=['active', 'created_at'], name='idx_ribrev_active_created'),
        ),
    ]
