# Generated by Django 5.2.4 on 2026-07-09 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_clean_order_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='RibbonColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
                ('hex_value', models.CharField(help_text='Например: #7A1430', max_length=7, verbose_name='HEX цвет')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ribbon/colors/%Y/%m/%d/', verbose_name='Фото/превью ленты')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Цвет ленты',
                'verbose_name_plural': 'Цвета лент',
                'ordering': ('sort_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='RibbonFont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
                ('font_family', models.CharField(help_text="Например: 'Romantique Script', cursive", max_length=160, verbose_name='CSS font-family')),
                ('font_file', models.FileField(blank=True, null=True, upload_to='ribbon/fonts/', verbose_name='Файл шрифта')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='ribbon/fonts/previews/%Y/%m/%d/', verbose_name='Превью шрифта')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Шрифт ленты',
                'verbose_name_plural': 'Шрифты лент',
                'ordering': ('sort_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='RibbonTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='ribbon/templates/%Y/%m/%d/', verbose_name='Превью шаблона')),
                ('layout_config', models.JSONField(blank=True, default=dict, help_text='JSON-конфиг макета. Можно оставить пустым.', verbose_name='Настройки шаблона')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Шаблон ленты',
                'verbose_name_plural': 'Шаблоны лент',
                'ordering': ('sort_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='RibbonTextColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
                ('hex_value', models.CharField(help_text='Например: #FFFFFF', max_length=7, verbose_name='HEX цвет')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Цвет текста на ленте',
                'verbose_name_plural': 'Цвета текста на ленте',
                'ordering': ('sort_order', 'title'),
            },
        ),
        migrations.AddField(
            model_name='ribbonorder',
            name='ribbon_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='main.ribboncolor', verbose_name='Цвет ленты'),
        ),
        migrations.AddField(
            model_name='ribbonorder',
            name='ribbon_font',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='main.ribbonfont', verbose_name='Шрифт'),
        ),
        migrations.AddField(
            model_name='ribbonorder',
            name='ribbon_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='main.ribbontemplate', verbose_name='Шаблон ленты'),
        ),
        migrations.AddField(
            model_name='ribbonorder',
            name='ribbon_text_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='main.ribbontextcolor', verbose_name='Цвет текста'),
        ),
    ]
